# Decision Tree & Random Forests 

In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
#Importing data
data = pd.read_csv('bank_imputed.csv')

In [3]:
data.head()

Unnamed: 0  RevolvingUtilizationOfUnsecuredLines  age  \
0           0                              0.766127   45   
1           1                              0.957151   40   
2           2                              0.658180   38   
3           3                              0.233810   30   
4           4                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     2   0.802982         9120.0   
1                                     0   0.121876         2600.0   
2                                     1   0.085113         3042.0   
3                                     0   0.036050         3300.0   
4                                     1   0.024926        12597.5   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                               13                        0   
1                                4                        0   
2                                2                        1   
3                                5                        0   
4                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                             6                                     0   
1                             0                                     0   
2                             0                                     0   
3                             0                                     0   
4                             1                                     0   

   NumberOfDependents  SeriousDlqin2yrs  
0                 2.0                 1  
1                 1.0                 0  
2                 0.0                 0  
3                 0.0                 0  
4                 0.0                 0

In [4]:
data.describe()

Unnamed: 0  RevolvingUtilizationOfUnsecuredLines           age  \
count  65535.000000                          65535.000000  65535.000000   
mean   32767.000000                              5.091486     52.195148   
std    18918.469283                            209.579093     14.790427   
min        0.000000                              0.000000     21.000000   
25%    16383.500000                              0.029803     41.000000   
50%    32767.000000                              0.156481     52.000000   
75%    49150.500000                              0.564614     63.000000   
max    65534.000000                          29110.000000    107.000000   

       NumberOfTime30-59DaysPastDueNotWorse     DebtRatio  MonthlyIncome  \
count                          65535.000000  65535.000000   65535.000000   
mean                               0.423819      0.664253    5867.527298   
std                                4.219182      0.689893    3039.982881   
min                                0.000000      0.000000       0.000000   
25%                                0.000000      0.174007    3905.000000   
50%                                0.000000      0.365817    5388.000000   
75%                                0.000000      0.869070    7382.000000   
max                               98.000000      1.911665   12597.500000   

       NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
count                     65535.000000             65535.000000   
mean                          8.413993                 0.269139   
std                           5.135781                 4.194458   
min                           0.000000                 0.000000   
25%                           5.000000                 0.000000   
50%                           8.000000                 0.000000   
75%                          11.000000                 0.000000   
max                          58.000000                98.000000   

       NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
count                  65535.000000                          65535.000000   
mean                       1.017258                              0.242679   
std                        1.131195                              4.181832   
min                        0.000000                              0.000000   
25%                        0.000000                              0.000000   
50%                        1.000000                              0.000000   
75%                        2.000000                              0.000000   
max                       54.000000                             98.000000   

       NumberOfDependents  SeriousDlqin2yrs  
count        65535.000000      65535.000000  
mean             0.739895          0.066911  
std              1.109174          0.249869  
min              0.000000          0.000000  
25%              0.000000          0.000000  
50%              0.000000          0.000000  
75%              1.000000          0.000000  
max             20.000000          1.000000

In [5]:
data.info()
#No null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 12 columns):
Unnamed: 0                              65535 non-null int64
RevolvingUtilizationOfUnsecuredLines    65535 non-null float64
age                                     65535 non-null int64
NumberOfTime30-59DaysPastDueNotWorse    65535 non-null int64
DebtRatio                               65535 non-null float64
MonthlyIncome                           65535 non-null float64
NumberOfOpenCreditLinesAndLoans         65535 non-null int64
NumberOfTimes90DaysLate                 65535 non-null int64
NumberRealEstateLoansOrLines            65535 non-null int64
NumberOfTime60-89DaysPastDueNotWorse    65535 non-null int64
NumberOfDependents                      65535 non-null float64
SeriousDlqin2yrs                        65535 non-null int64
dtypes: float64(4), int64(8)
memory usage: 6.0 MB


In [6]:
# Dropping first column

data = data.drop(["Unnamed: 0"],axis = 1)

In [7]:
data.columns

Index(['RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents', 'SeriousDlqin2yrs'],
      dtype='object')

In [8]:
# Splitting the data
X = data.drop(["SeriousDlqin2yrs"],axis = 1)
y = data['SeriousDlqin2yrs']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4, random_state = 101)

In [9]:
# Fitting the model for Decision Tree
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [10]:
# predictions
pred = classifier.predict(X_test)

In [11]:
# Evaluation metrics
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(pred,y_test))
print(classification_report(pred,y_test))
print(accuracy_score(pred,y_test))

[[22961  1287]
 [ 1496   470]]
              precision    recall  f1-score   support

           0       0.94      0.95      0.94     24248
           1       0.27      0.24      0.25      1966

    accuracy                           0.89     26214
   macro avg       0.60      0.59      0.60     26214
weighted avg       0.89      0.89      0.89     26214

0.8938353551537347


In [12]:
# Splitting the data for Random Forest
X = data.drop(["SeriousDlqin2yrs"],axis = 1)
y = data['SeriousDlqin2yrs']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4, random_state = 101)

In [14]:
#selecting features with Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
select = SelectFromModel(RandomForestClassifier(n_estimators = 100, random_state = 101))
select.fit(X_train,y_train)

SelectFromModel(estimator=RandomForestClassifier(random_state=101))

In [15]:
X_new = X_train.columns[(select.get_support())]
X_new

Index(['RevolvingUtilizationOfUnsecuredLines', 'age', 'DebtRatio',
       'MonthlyIncome'],
      dtype='object')

In [16]:
# Defining new X and y and splitting again
y = data[["SeriousDlqin2yrs"]]
x= data[['RevolvingUtilizationOfUnsecuredLines', 'age', 'DebtRatio',
       'MonthlyIncome']]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4, random_state = 101)

In [17]:
# Fitting the model for Random Forest
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100)
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [18]:
# predictions
pred = classifier.predict(X_test)

In [19]:
# Evaluation metrics
print(confusion_matrix(pred,y_test))
print(classification_report(pred,y_test))
print(accuracy_score(pred,y_test))
# The accuarcy has improved with using Random Forest Classifier

[[24151  1451]
 [  306   306]]
              precision    recall  f1-score   support

           0       0.99      0.94      0.96     25602
           1       0.17      0.50      0.26       612

    accuracy                           0.93     26214
   macro avg       0.58      0.72      0.61     26214
weighted avg       0.97      0.93      0.95     26214

0.932974746318761


In [20]:
# Checking for imbalance data
np.unique(y_train,return_counts=True)
#We have substantially more zeros that ones

(array([0, 1], dtype=int64), array([36693,  2628], dtype=int64))

In [21]:
#importing libraries for OverSampling
import imblearn
from imblearn import over_sampling
from imblearn.over_sampling import SMOTE

In [22]:
# Splitting the data for oversampling
X = data.drop(["SeriousDlqin2yrs"],axis = 1)
y = data['SeriousDlqin2yrs']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4, random_state = 101)

In [25]:
# Creating more copies of ones using oversampling 
sm = imblearn.over_sampling.SMOTE()
X_train,y_train = sm.fit_sample(X_train,y_train)

In [28]:
np.unique(y_train,return_counts=True)
# Data is balanced now

(array([0, 1], dtype=int64), array([36693, 36693], dtype=int64))

In [29]:
# Running Random forest again
classifier = RandomForestClassifier(n_estimators = 100)
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [30]:
# predictions
pred = classifier.predict(X_test)

In [32]:
# Evaluation metrics
print(confusion_matrix(pred,y_test))
print(classification_report(pred,y_test))
print(accuracy_score(pred,y_test))

[[22507  1009]
 [ 1950   748]]
              precision    recall  f1-score   support

           0       0.92      0.96      0.94     23516
           1       0.43      0.28      0.34      2698

    accuracy                           0.89     26214
   macro avg       0.67      0.62      0.64     26214
weighted avg       0.87      0.89      0.88     26214

0.8871213855191882
